#' Write PECBMS arguments input files for each species
#'
#' @param Spp_selection a tibble with columns 'EuringCode', 'Year_First', 'TFC_Basetime',
#' 'TCF_Slope_From' and 'Stratum'.
#' @param folderPath character. Name of the subdirectory in which to save the
#' CSV files. If the folder does not exist yet, it will be generated by the 
#' function. 
#'
#' @return a dataframe listing file names and analysis arguments for all species
#' that are part of the PECBMS analysis. Additionally saves argument input file
#' for each species as CSV in designated folder. 
#' 
#' @export
#'
#' @examples

setupInputFiles_PECBMS_trimShell <- function(Spp_selection, folderPath){
  

  ## Add the species-specific starting year ("Year_from" variable)
  Spp_selection <- Spp_selection %>%
    dplyr::mutate(Year_from = dplyr::case_when(Year_First %in% c(2006, 2007) ~ 2007,
                                               Year_First == 2008 ~ 2008))

  ## Check for other starting years
  if(any(is.na(Spp_selection$Year_from))){
    warning("Data contains species with a first year that is not 2006, 2007, or 2008.")
  }
  
  ## Setup argument file for all species
  argument_file <- data.frame(
    File =  paste0('BMP_', Spp_selection$EURINGCode,'_1_63'),
    Base_year_first_year = 2008,
    Base_year_last_year = 2008,
    Changepoints = "all",
    Serial_correlation = "TRUE",
    Overdispersion = "TRUE",
    Presence_weights = "FALSE",
    Presence_monthfactors = "FALSE",
    Year_from = Spp_selection$Year_from,
    Save_fitted_values = "TRUE"
  ) 
  
  ## Create directory for saving files if neccessary
  if(!dir.exists(folderPath)){dir.create(folderPath)}
  
  ## Save argument file for each species as .csv in specified directory
  for(i in 1:nrow(Spp_selection)){
    
    write.csv2(argument_file[i, ], 
               paste0(folderPath, "/", argument_file$File[i], "_arg_input_stratum.csv"), 
               row.names = FALSE)
  
  }

  ## Return arguments dataframe
  return(argument_file)
}