---
title: "Template for indicator documentation"
output:
  pdf_document
---

<!-- This is a template for how to document the indicator analyses. 
Make a copy of this file and sore it in the same folder (indicators/workingFiles/) 
before starting. This is a working file. It is also a stand-alone Rmd file
inside a bookdown project. Therefore, to knit the file for preview reasons,
you need to type rmarkdown::render("indicators/workingFiles/template.Rmd") 
in the console, as the the usual Ctrl + Alt + k will not work. When the analyses is complete,
Anders Kolstad or someone else will perform a rapid code review, making sure 
the analyses is repeatable by someone else. Be therefore very careful to annotate 
and comment on every step in the analysis. When completed, Anders will make a copy
of the working file and put it in the folder below (indicators/). After modifying it
slightly (mainly removing the top YAML header) the output will become available 
on the website (https://ninanor.github.io/ecosystemCondition/) -->


<!-- Replace 'indicator name' with yor own indicator name  -->
# Indicator name {-}

<br />

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
```


<!-- Fill in which ecosystem the indicator belongs to, as well as the ecosystem characteristic it should be linked to. It's OK to use some Norwegian here -->

```{r, echo=F}
Ecosystem <- "" # e.g. "Skog og fjell"
Egenskap  <- "" # e.g. "Primærproduksjon"
ECT       <- "" # e.g. "Structural state characteristic"
Contact   <- "" # e.g. "Anders Kolstad"
```

```{r, echo=F}
metaData <- data.frame(Ecosystem,
                       "Økologisk egenskap" = Egenskap,
                       "ECT class" = ECT)
knitr::kable(metaData)
```

<!-- Don't remove these three html lines -->
<br />
<br />
<hr />



<!-- Document you work below. Data can be stored on NINA server, harvested using API or similar, or if it is not too big, stored under /data/ on this repository -->


Here's a nice plot,   Blablabla
```{r, fig.cap="This is my figure caption"}
plot(rnorm(10,10,10))
```

