<!-- TEMPLATE -->

<!-- This is a template for how to document the indicator analyses. Make a copy of this file and sore it in the same folder (indicators/) before starting.  -->


<!-- Replace 'indicator name' with yo own indicator name  -->
# Indicator name {-}

<br />

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
```


<!-- Fill in which ecosystem the indicator belongs to, as well as the ecosystem characteristic it should be linked to. It's OK to use some Norwegian here -->

```{r, echo=F}
Ecosystem <- "" # e.g. "Skog og fjell"
Egenskap  <- "" # e.g. "Primærproduksjon"
ECT       <- "" # e.g. "Structural state characteristic"
```

```{r, echo=F}
metaData <- data.frame(Ecosystem,
                       "Økologisk egenskap" = Egenskap,
                       "ECT class" = ECT)
knitr::kable(metaData)
```

<!-- Don't remove these threehtml lines -->
<br />
<br />
<hr />



<!-- Document you work below. Data can be stored on NINA server, harvested using API or similar, or if it is not too big, stored under /data/ on this repository -->


Here's a nice plot,   Blablabla
```{r, fig.cap="This is my figure caption"}
plot(rnorm(10,10,10))
```

