---
title: "Showcase some database functionality"
author: "Jens Å"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  NinaR::jensAnalysis:
    highlight: tango
    fig_caption: yes
    toc: yes
---


```{r, include = F}
# Some common packages, loading rmarkdown doesn't like the messages from tidyverse, so we don't include this in the document'
require(tidyverse)
require(DBI)
require(RPostgres)
require(ggplot2)
require(xtable)
require(NinaR)
```


```{r setup, include=FALSE}
# This is optional
# I choose the 'styler' package for tidying the code to preserve indentations
# I set the cutoff for code tidying to 60, but this doesn't currently work with styler.
# Set tidy = True to get the knitr default
# I want all figures as png and pdf in high quality in a subfolder called figure

knitr::opts_chunk$set(
  echo = TRUE,
  tidy = "styler",
  dev = c("png", "pdf"),
  dpi = 600,
  fig.path = "figure/"
)

options(
  xtable.comment = F,
  xtable.include.rownames = F,
  nina.logo.y.pos = 0.15
)
palette(ninaPalette())
```

Intro
======
Not much here yet, only some quick commands.

```{r}
library(Norimon)
```
```{r}
connect_to_insect_db()
```

```{r}
require(DBI)
 require(dplyr)
locations <- tbl(con,
                 Id(schema = "locations",
                    table = "localities"))


```
```{r}
locations
```
```{r}
require(sf)

locations_sf <- read_sf(con,
                 Id(schema = "locations",
                    table = "localities"))


```
```{r}
require(ggplot2)

ggplot(locations_sf) +
  geom_sf(aes(fill = habitat_type))
```


New locality function
---------

```{r}
insect_localities_sf <- get_localities()
```

```{r}
insect_localities <- get_localities(as_sf = FALSE)
```




